### ISSUE TITLE
Can't create an instance with an empty list of tags.

### ISSUE THREAD

**Issue by jdart** [webworka/Tagedit#3]
The plugin works great when you already have a list of tags to work with but I can't see a way to create an instance of Tagedit with no existing tags. Imagine creating a new wordpress post with no tags.

``` html
<div id="some-id"></div>
```

``` javascript
jQuery(function($){
  $("#some-id input.tag").tagedit();
});
```

The selector doesn't match and so it would have no effect.

What do you think about changing the way you initialize Tagedit to require the input selector as an option.

``` javascript
jQuery(function($){
  $("#some-id").tagedit({ inputSelector: 'input.tag' });
});
```

It could even be a default which would make creating an instance more concise. 

What do you think?

**Comment by webworka** [comment]
Hi,
if you want to have an empty list you can put an empty input with empty brackets: name="somename[]". I do it this way in all my projects.

Nevertheless the idea is interesting to start optionally with an empty list. I'll check this.

Oliver

**Comment by webworka** [comment]
Hi Jonathan,

I had a look on your implementation with the input selector. The intention of the plugin was to put several input fields into one big. Because of that I initialize the plugin on the inputs and not on the container around the input fields. 
I did this because the form should (theoretically) also work without js.

So I think, for me, the best way is to leave this behaviour as it is. In all the frameworks (i.e. Zend) I use with this plugin it's not possible to create a form element without creating an element in the DOM. Therfore it is possible to start with an empty list:

``` html

<form action="server/formtarget.php" method="post" id="tagform-editonly">
        <p>
            <input type="text" name="tag[]" value="" class="tag" />
            <input type="submit" name="save" value="Save"/>
        </p>
</form>

```

``` javascript

$( 'input.tag').tagedit();

```
